name: CD NestJs Real world
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCOUNT_ID:AWS_ACCOUNT_ID: '${{ secrets.NRW_AWS_ACCOUNT_ID }}'
      AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
      AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Deploy Artifact
        run: ./scripts/ci/deploy-artifact.sh